import { Platform, StyleSheet } from 'react-native';

export const colors = {
  page: '#F1F5F9',
  leftFrom: '#1D4ED8',
  leftTo: '#312E81',
  panel: '#FFFFFF',
  textMain: '#0F172A',
  textSubtle: '#64748B',
  border: '#D6DCE6',
  primary: '#2563EB',
  primaryDark: '#1D4ED8',
  white: '#FFFFFF',
  success: '#22C55E',
};

export const MIN_WIDTH_TWO_COLUMNS = 980;

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: colors.page,
  },
  scrollContent: {
    flexGrow: 1,
  },
  shell: {
    flex: 1,
    flexDirection: 'column',
  },
  shellRow: {
    flexDirection: 'row',
  },
  leftPanel: {
    backgroundColor: colors.leftFrom,
    paddingHorizontal: 44,
    paddingTop: 40,
    paddingBottom: 30,
  },
  leftPanelDesktop: {
    flex: 0.5,
    minHeight: 760,
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  productIcon: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.94)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  productTitle: {
    color: colors.white,
    fontSize: 38,
    fontWeight: '800',
  },
  productSub: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 26,
    fontWeight: '500',
    marginTop: 2,
  },
  leftHeadline: {
    marginTop: 38,
    color: colors.white,
    fontSize: 50,
    lineHeight: 58,
    fontWeight: '900',
    maxWidth: 640,
  },
  leftDescription: {
    marginTop: 22,
    color: 'rgba(255,255,255,0.82)',
    fontSize: 28,
    lineHeight: 38,
    fontWeight: '500',
    maxWidth: 640,
  },
  bulletsWrap: {
    marginTop: 26,
    gap: 14,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  bulletDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(34,197,94,0.15)',
    borderWidth: 1,
    borderColor: '#22C55E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bulletText: {
    color: 'rgba(255,255,255,0.88)',
    fontSize: 24,
    fontWeight: '500',
  },
  statsRow: {
    marginTop: 'auto',
    paddingTop: 22,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.16)',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statItem: {
    minWidth: 96,
  },
  statNumber: {
    color: colors.white,
    fontSize: 42,
    fontWeight: '900',
  },
  statLabel: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 22,
    fontWeight: '500',
    marginTop: 1,
  },
  rightPanel: {
    backgroundColor: colors.page,
    paddingHorizontal: 32,
    paddingTop: 22,
    paddingBottom: 26,
    justifyContent: 'center',
  },
  rightPanelDesktop: {
    flex: 0.5,
  },
  langSelector: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  langButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: colors.panel,
  },
  langButtonActive: {
    borderColor: colors.primary,
    backgroundColor: '#EEF4FF',
  },
  langButtonText: {
    color: colors.textSubtle,
    fontSize: 17,
    fontWeight: '700',
  },
  langButtonTextActive: {
    color: colors.primary,
  },
  formWrap: {
    maxWidth: 640,
    width: '100%',
    alignSelf: 'center',
    marginTop: 18,
  },
  topBadge: {
    alignSelf: 'center',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
    backgroundColor: '#E8F0FF',
  },
  topBadgeText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  title: {
    marginTop: 14,
    textAlign: 'center',
    color: colors.textMain,
    fontSize: 44,
    lineHeight: 48,
    fontWeight: '900',
  },
  subtitle: {
    marginTop: 10,
    textAlign: 'center',
    color: colors.textSubtle,
    fontSize: 24,
    fontWeight: '500',
  },
  socialButtonWide: {
    marginTop: 22,
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 15,
    backgroundColor: colors.panel,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  socialButtonHalfRow: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 10,
  },
  socialButtonHalf: {
    flex: 1,
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 15,
    backgroundColor: colors.panel,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  socialText: {
    color: '#334155',
    fontSize: 25,
    fontWeight: '700',
  },
  dividerRow: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border,
  },
  dividerText: {
    color: colors.textSubtle,
    fontSize: 17,
    fontWeight: '500',
  },
  fieldWrap: {
    marginTop: 18,
  },
  label: {
    color: '#334155',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 8,
  },
  inputFrame: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 15,
    backgroundColor: colors.panel,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 10,
  },
  inputError: {
    borderColor: '#DC2626',
    backgroundColor: '#FEF2F2',
  },
  input: {
    flex: 1,
    color: colors.textMain,
    fontSize: 22,
    paddingVertical: Platform.select({ ios: 12, android: 10, default: 10 }),
  },
  error: {
    marginTop: 6,
    color: '#DC2626',
    fontSize: 15,
    fontWeight: '500',
  },
  helperRow: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.4,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.panel,
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  rememberText: {
    color: '#334155',
    fontSize: 21,
    fontWeight: '600',
  },
  forgotText: {
    color: colors.primary,
    fontSize: 21,
    fontWeight: '700',
  },
  submitButton: {
    marginTop: 20,
    minHeight: 56,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOpacity: 0.32,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  submitButtonPressed: {
    backgroundColor: colors.primaryDark,
  },
  submitButtonText: {
    color: colors.white,
    fontSize: 24,
    fontWeight: '800',
  },
  secureRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secureText: {
    color: colors.textSubtle,
    fontSize: 18,
    fontWeight: '500',
  },
  requestRow: {
    marginTop: 18,
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 4,
  },
  requestPrefix: {
    color: colors.textSubtle,
    fontSize: 18,
    fontWeight: '500',
  },
  requestLink: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '700',
  },
});
